spec:
  name: wishlist-dd
  services:
    - name: api
      environment_slug: php
      github:
        repo: user/repo
        branch: main
        deploy_on_push: true
      run_command: "php -S 0.0.0.0:${PORT} -t public public/index.php"
      http_port: 8080
      instance_size_slug: basic-xxs
      instance_count: 1
      routes:
        - path: /api
      envs:
        - key: APP_ENV
          value: production
          scope: RUN_AND_BUILD_TIME
  static_sites:
    - name: frontend
      github:
        repo: user/repo
        branch: main
        deploy_on_push: true
      source_dir: frontend
      build_command: "npm ci && npm run build"
      output_dir: dist
      routes:
        - path: /
      catchall_document: index.html
      envs:
        - key: VITE_API_BASE
          value: /api
          scope: BUILD_TIME
